# Generated by Django 4.1.3 on 2022-12-25 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_webpage_image_1_webpage_image_2_webpage_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ogg', 'mp4', 'webm'])]),
        ),
    ]
